name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install django==3.2
          pip install -r requirements.txt  # Убедитесь, что у вас есть файл requirements.txt с зависимостями

      - name: Run migrations
        run: |
          python manage.py migrate --noinput  # Добавьте --noinput, чтобы избежать запроса на ввод

      - name: Run tests
        run: |
          python manage.py test
